name: ctpt
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - cryptography=39.0.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - flit-core=3.8.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.6.0.25
  - libcurand=10.3.2.56
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1t
  - pillow=9.4.0
  - pip=23.0.1
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.10
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.6.3
  - sqlite=3.41.1
  - sympy=1.11.1
  - tk=8.6.12
  - torchaudio=2.0.0
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.15
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.4
  - pip:
    - absl-py==1.4.0
    - accelerate==0.24.1
    - appdirs==1.4.4
    - asttokens==2.2.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.0
    - blessed==1.20.0
    - cachetools==5.3.0
    - charset-normalizer==2.0.4
    - click==8.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - decorator==5.1.1
    - diffusers==0.23.0
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - executing==1.2.0
    - flake8==3.7.9
    - fonttools==4.39.3
    - fsspec==2023.10.0
    - ftfy==6.1.1
    - future==0.18.3
    - gdown==4.7.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.17.1
    - google-auth-oauthlib==1.0.0
    - gpustat==1.0.0
    - grpcio==1.53.0
    - huggingface-hub==0.17.3
    - importlib-metadata==6.8.0
    - ipdb==0.13.13
    - ipython==8.12.0
    - isort==4.3.21
    - jedi==0.18.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - littleutils==0.2.2
    - markdown==3.4.3
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mccabe==0.6.1
    - mpmath==1.2.1
    - nvidia-ml-py==11.495.46
    - oauthlib==3.2.2
    - ogb==1.3.5
    - outdated==0.2.2
    - packaging==23.1
    - pandas==1.5.3
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.38
    - protobuf==4.22.1
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.5.0
    - pycparser==2.21
    - pyflakes==2.1.1
    - pygments==2.14.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0
    - regex==2023.3.23
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - safetensors==0.4.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sentry-sdk==1.19.0
    - setproctitle==1.3.2
    - six==1.16.0
    - smmap==5.0.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - tabulate==0.9.0
    - tb-nightly==2.13.0a20230401
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tokenizers==0.14.1
    - tomli==2.0.1
    - tqdm==4.65.0
    - traitlets==5.9.0
    - transformers==4.35.0
    - wandb==0.14.0
    - wcwidth==0.2.6
    - werkzeug==2.2.3
    - wilds==1.2.2
    - yacs==0.1.8
    - yapf==0.29.0
    - zipp==3.17.0

